### PR TITLE
Feature/term config dropdown

### PR DESCRIPTION
**Pull request by ltwheeler**
Migrates the budget config term modal into a term dropdown

Issues:
https://trello.com/c/mkYbtRdU/1710-budgetview-migrate-term-config-modal-into-term-filter-dropdown-ala-course-view

### CODE REVIEW

**Comment by cthielen** [comment]
I see the termFilter component is in the budget module directory. Since the same control is useful on other pages, how much work is it to identify the other pages with term filters and make this component reusable? That strikes me as the proper component architecture.

**Comment by cthielen** [comment]
Dropdown icon size does not match size of nearby Download and Print buttons.

**Comment by cthielen** [comment]
Dropdown menu should collapse when someone clicks away, e.g. on the whitespace elsewhere in the page.

**Comment by cthielen** [comment]
out

Term selector does not appear to work consistently.

**Comment by ltwheeler** [comment]
Making it a generic term selector seems reasonable.

Refactoring it to remove 'budget specific' concepts and elevating to the sharedApp should be 30min at most.

Implementing it across IPA might take a few hours, there are some stylistic differences across IPA that will need to be cleaned up and the 'term' data modeling varies.

**Comment by ltwheeler** [comment]
I wasn't able to replicate the inconsistent behavior bug you demonstrated in the video, do you recall what workgroup/year/browser you were testing with?

**Comment by cthielen** [comment]
Bug is still present in latest changes on May 21 at 1:53pm. Using Safari 11.1 with 'develop' backend and this PR for the frontend. Database from IPA_2018-05-01_06h25m.Tuesday.sql. Logged in, went straight to budget (workgroup defaulted to DSS IT, year 2018-19).

It appears to only happen when you click the graphical checkbox itself. Clicking the words to the right of the checkbox seems to be working.

**Pull request merged**
