### PR TITLE
Add blank option to clear out already set times

### PR DESCRIPTION
**Pull request by ltwheeler**

### CODE REVIEW

**Comment by cthielen** [comment]
[Untitled.zip](https://github.com/ucdavis/ipa-client-angular/files/1293448/Untitled.zip)

**Comment by ltwheeler** [comment]
I just rebuilt the time pattern selector, and it should be more intuitive/consistent in its behavior now, the old one was definitely not good. This should also make the eventual condensing of the standard / non-standard time pattern UI's much easier

**Comment by cthielen** [comment]
Two issues, one bug and one feature tweak:

1) Feature tweak: blanking an option should only blank itself and anything to its right instead of the entire form
2) Bug: If you set a time and then blank it, and then select 50min (or 80, etc.), the system fills in a previously used weekday and if you then click a time, it fails to render. Refreshing the page makes this bug appear to be due to the pre-filled day not being saved correctly.

**Comment by cthielen** [comment]
I believe we're waiting on additional commits to fix some CSS issues related to scrolling here. Once that's in I'll do another Q&A.

**Pull request merged**
